name: Workflow

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  move_to_bug_report:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Bug report
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: Alstom-WebFdl
          column-name: "Remontée de bugs"
          issue-number: ${{ github.event.issue.number }}
        if: contains(github.event.issue.labels.*.name, 'bug')