name: Workflow

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  move_to_column:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: Alstom-WebFdl
          column-name: "À faire"
          issue-number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.event.issue.labels.*.name, 'enhancement')

      - uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: Alstom-WebFdl
          column-name: "Remontée de bugs"
          issue-number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.event.issue.labels.*.name, 'bug')